yarnPath: .yarn/releases/yarn-4.1.1.cjs
cloneConcurrency: 4
compressionLevel: mixed
defaultSemverRangePrefix: ""
enableGlobalCache: false
enableHardenedMode: true
pnpEnableEsmLoader: true
pnpIgnorePatterns:
  - ./dist/**
